---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat
spec:
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:8.5-a1
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
            hostPort: 8090
